name: Maze Runner

on: [push, pull_request]

jobs:
  maze-runner:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev net-tools

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - run: bundle exec maze-runner --no-source
      env:
        PYTHON_TEST_VERSION: ${{ matrix.python-version }}
